services:
  - type: web
    runtime: static
    name: repleetfrontend
    repo: https://github.com/GonzaloAllenPerez444/RepleetFrontend
    branch: main
    rootDir: repleetfrontend.client
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://repleet.azurewebsites.net
    redirects:
      - source: "/*"
        destination: "/index.html"
        statusCode: 200





















